# Generated by Django 4.2.9 on 2024-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_in',
            new_name='comment_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_in',
            new_name='post_time',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новости')], default='NE', max_length=2),
        ),
    ]
